platform :ios, '8.0'
#use_frameworks!
inhibit_all_warnings!

target 'CJRichScanDemo' do
    pod 'Masonry', '~> 1.1.0'
    pod 'CJMedia/CJValidateAuthorizationUtil'
    
    pod 'LBXScan'
end

target 'CJRichScanDemoTests' do
   
end
